#!/usr/bin/env node

import { execFileSync } from 'child_process';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

function usage() {
  process.stdout.write(`Sync all workspace package versions from the single source of truth (VERSION file).

Usage:
  node ./scripts/sync-version.mjs [--check]

Options:
  --check   Validate that all component versions match the VERSION file.
            Exits with code 0 if they match, or 1 if any file diverges.
`);
}

const args = process.argv.slice(2);
if (args.includes('-h') || args.includes('--help')) {
  usage();
  process.exit(0);
}

const versionFilePath = path.resolve(rootDir, 'VERSION');

// Bootstrap check: read from VERSION file
if (!fs.existsSync(versionFilePath)) {
  process.stderr.write(`Error: VERSION file not found at ${versionFilePath}\n`);
  process.stderr.write(`Please create it with the current CalVer version (e.g. 2026.6.13).\n`);
  process.exit(1);
}

const version = fs.readFileSync(versionFilePath, 'utf8').trim();

if (!/^\d{4}\.\d{1,2}\.\d+$/.test(version)) {
  process.stderr.write(`Error: Invalid CalVer in VERSION file: "${version}"\n`);
  process.stderr.write(`Expected format: YYYY.M.PATCH (e.g. 2026.6.13)\n`);
  process.exit(1);
}

function runNpm(npmArgs) {
  execFileSync('npm', npmArgs, {
    cwd: rootDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf8',
  });
}

const paths = {
  rootPkg: path.resolve(rootDir, 'package.json'),
  backendPkg: path.resolve(rootDir, 'backend', 'package.json'),
  frontendPkg: path.resolve(rootDir, 'frontend', 'package.json'),
  sharedPkg: path.resolve(rootDir, 'shared', 'package.json'),
  versionTs: path.resolve(rootDir, 'shared', 'src', 'lib', 'version.ts'),
};

if (args.includes('--check')) {
  let isConsistent = true;

  try {
    const rootPkg = JSON.parse(fs.readFileSync(paths.rootPkg, 'utf8'));
    if (rootPkg.version !== version) {
      process.stderr.write(`Version mismatch in package.json: expected ${version}, found ${rootPkg.version}\n`);
      isConsistent = false;
    }

    const backendPkg = JSON.parse(fs.readFileSync(paths.backendPkg, 'utf8'));
    if (backendPkg.version !== version) {
      process.stderr.write(`Version mismatch in backend/package.json: expected ${version}, found ${backendPkg.version}\n`);
      isConsistent = false;
    }

    const frontendPkg = JSON.parse(fs.readFileSync(paths.frontendPkg, 'utf8'));
    if (frontendPkg.version !== version) {
      process.stderr.write(`Version mismatch in frontend/package.json: expected ${version}, found ${frontendPkg.version}\n`);
      isConsistent = false;
    }

    const sharedPkg = JSON.parse(fs.readFileSync(paths.sharedPkg, 'utf8'));
    if (sharedPkg.version !== version) {
      process.stderr.write(`Version mismatch in shared/package.json: expected ${version}, found ${sharedPkg.version}\n`);
      isConsistent = false;
    }

    if (!fs.existsSync(paths.versionTs)) {
      process.stderr.write(`File missing: ${paths.versionTs}\n`);
      isConsistent = false;
    } else {
      const tsContent = fs.readFileSync(paths.versionTs, 'utf8');
      if (!tsContent.includes(`VERSION = '${version}'`)) {
        process.stderr.write(`Version mismatch in shared/src/lib/version.ts: expected ${version}\n`);
        isConsistent = false;
      }
    }
  } catch (error) {
    process.stderr.write(`Failed during version validation: ${error.message}\n`);
    process.exit(1);
  }

  if (isConsistent) {
    process.stdout.write(`All version metadata files are consistently in sync with version: ${version}\n`);
    process.exit(0);
  } else {
    process.stderr.write(`Version verification failed. Run "node scripts/sync-version.mjs" to synchronize.\n`);
    process.exit(1);
  }
}

// Perform actual synchronization
try {
  process.stdout.write(`Syncing workspace packages to version: ${version}\n`);

  runNpm(['pkg', 'set', `version=${version}`]);
  runNpm(['pkg', 'set', '--workspace=nexkan-backend', `version=${version}`]);
  runNpm(['pkg', 'set', '--workspace=nexkan-frontend', `version=${version}`]);
  runNpm(['pkg', 'set', '--workspace=@nexkan/shared', `version=${version}`]);

  process.stdout.write('Regenerating package-lock.json...\n');
  runNpm(['install', '--package-lock-only']);

  process.stdout.write(`Writing ${paths.versionTs}...\n`);
  fs.writeFileSync(
    paths.versionTs,
    `// Generated by scripts/sync-version.mjs\nexport const VERSION = '${version}';\n`
  );

  process.stdout.write('Building @nexkan/shared...\n');
  runNpm(['run', 'build', '--workspace=@nexkan/shared']);

  process.stdout.write(`Successfully synced and compiled all packages to version ${version}\n`);
} catch (error) {
  process.stderr.write(`Failed to sync version: ${error.message}\n`);
  process.exit(1);
}
