#!/usr/bin/env node

const { execFileSync } = require('child_process');
const path = require('path');

const rootDir = path.resolve(__dirname, '..');

function usage() {
  process.stdout.write(`Sync all workspace package versions from a single source of truth (root package.json).

Usage:
  node ./scripts/sync-version.js [VERSION]

Arguments:
  VERSION   CalVer in YYYY.M.PATCH or vYYYY.M.PATCH format.
            If omitted, auto-increments the patch version for the current month.

Examples:
  node ./scripts/sync-version.js
  node ./scripts/sync-version.js 2026.6.1
  node ./scripts/sync-version.js v2026.6.1

Notes:
  - Root package.json is the single source of truth.
  - This script updates root + backend + frontend + shared versions.
  - package-lock.json is refreshed to keep version metadata in sync.
`);
}

function runNpm(args) {
  execFileSync('npm', args, {
    cwd: rootDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf8',
  });
}

function getRootVersion() {
  const out = execFileSync('npm', ['pkg', 'get', 'version'], {
    cwd: rootDir,
    stdio: ['ignore', 'pipe', 'pipe'],
    encoding: 'utf8',
  });
  return out.trim().replace(/^"|"$/g, '');
}

function getNextCalVer(currentVersion) {
  const now = new Date();
  const currentYear = now.getFullYear();
  const currentMonth = now.getMonth() + 1;

  try {
    const parts = currentVersion.split('.').map(Number);
    if (parts.length < 3 || parts.some(isNaN)) {
      return `${currentYear}.${currentMonth}.1`;
    }
    const prevYear = parts[0];
    const prevMonth = parts[1];
    const prevPatch = parts[2];

    // If the year or month has changed, reset patch/minor-fix to 1
    if (currentYear > prevYear || (currentYear === prevYear && currentMonth > prevMonth)) {
      return `${currentYear}.${currentMonth}.1`;
    }

    // Otherwise, increment the patch/minor-fix number by 1
    return `${prevYear}.${prevMonth}.${prevPatch + 1}`;
  } catch (e) {
    return `${currentYear}.${currentMonth}.1`;
  }
}

const arg = process.argv[2];
if (arg === '-h' || arg === '--help') {
  usage();
  process.exit(0);
}

let version;
if (arg) {
  version = arg.replace(/^v/, '');
  if (!/^\d{4}\.\d{1,2}\.\d+$/.test(version)) {
    process.stderr.write(`Invalid CalVer: ${arg}\n`);
    process.stderr.write('Expected: YYYY.M.PATCH or vYYYY.M.PATCH\n\n');
    usage();
    process.exit(1);
  }
} else {
  try {
    const currentVersion = getRootVersion();
    version = getNextCalVer(currentVersion);
  } catch (error) {
    const now = new Date();
    version = `${now.getFullYear()}.${now.getMonth() + 1}.1`;
  }
}

try {
  runNpm(['pkg', 'set', `version=${version}`]);
  const rootVersion = getRootVersion();

  runNpm(['pkg', 'set', '--workspace=nexkan-backend', `version=${rootVersion}`]);
  runNpm(['pkg', 'set', '--workspace=nexkan-frontend', `version=${rootVersion}`]);
  runNpm(['pkg', 'set', '--workspace=@nexkan/shared', `version=${rootVersion}`]);

  runNpm(['install', '--package-lock-only']);

  // Write version to shared package
  const fs = require('fs');
  const versionFile = path.resolve(rootDir, 'shared', 'src', 'lib', 'version.ts');
  fs.writeFileSync(
    versionFile,
    `// Generated by scripts/sync-version.js\nexport const VERSION = '${rootVersion}';\n`
  );
  process.stdout.write(`Updated shared version file: ${versionFile}\n`);

  // Build the shared workspace so it's compiled and ready for backend/frontend
  process.stdout.write('Building @nexkan/shared...\n');
  runNpm(['run', 'build', '--workspace=@nexkan/shared']);

  process.stdout.write(`Synced versions to ${rootVersion}\n`);
  process.stdout.write('Root source of truth: package.json\n');
} catch (error) {
  const message = error && error.message ? error.message : String(error);
  process.stderr.write(`Failed to sync version: ${message}\n`);
  process.exit(1);
}
