import { packageVersion, npmLockVersion } from './version-control.mjs';

export default {
  targets: [
    ...['package.json', 'backend/package.json', 'frontend/package.json', 'shared/package.json'].map((path) => ({ path, transform: packageVersion })),
    { path: 'package-lock.json', transform: (text, version) => npmLockVersion(text, version, ['backend', 'frontend', 'shared']) },
    { path: 'shared/src/lib/version.ts', generated: true, transform: (_text, version) => `// Generated by scripts/sync-version.mjs\nexport const VERSION = '${version}';\n` },
  ],
  build: [
    { command: 'npm', args: ['run', 'build', '--workspace=@nexkan/shared'] },
    { command: 'docker', args: ['compose', 'build'] },
  ],
};
